# This sets the Jekyll theme for GitHub Pages
theme: jekyll-theme-minimal

# Other available themes:
# - jekyll-theme-cayman
# - jekyll-theme-slate
# - jekyll-theme-hacker
# - jekyll-theme-midnight